name: Build and Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
    GOFLAGS: "-buildvcs=false"

jobs:
  build:
    runs-on: ubuntu-latest
    container: manetu/unified-builder:v3.0
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile
      run: make all

    - name: Upload binaries artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: target

  test:
    runs-on: ubuntu-latest
    needs: build
    container: ghcr.io/manetu/ci-tools:3.1
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download binaries artifact
      uses: actions/download-artifact@v4
      with:
        name: compiled-binaries
        path: target

    - run: |
        chmod +x target/*
        cp target/* /usr/local/bin

        docker-compose -f docker/docker-compose/integrate.yml up -d
