name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
    GOFLAGS: "-buildvcs=false"

jobs:
  test:
    runs-on: ubuntu-latest
    container: manetu/unified-builder:v3.0
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile
      run: make all

    - name: Run third-party services
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker/docker-compose/integrate.yml"

    - name: Run integration tests
      run: docker run --network integration-test -v $PWD:/work -w /work manetu/unified-builder:v3.0-jre ./integrate.sh
